import type { Metadata } from 'next'
import './globals.css'
import { Dela_Gothic_One } from 'next/font/google'
import Navbar from '@/components/ui/Navbar'

const dela = Dela_Gothic_One({
  subsets: ['cyrillic'],
  weight: '400',
  display: 'swap',
  variable: '--font-dela',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`antialised ${dela.variable}`}>
        <Navbar />
        {children}
      </body>
    </html>
  )
}
